### ISSUE TITLE
Long Memo Overflows Outside Container

### ISSUE THREAD

**Issue by lee-jongwoo** [AppDevelopers2021/studia#12]
<img width="1312" alt="Screen Shot 2021-12-13 at 6 53 30 PM" src="https://user-images.githubusercontent.com/70620386/145792020-b11f909c-f7dc-4ef7-a4cb-18a1ccfb2e02.png">
Like This

**Comment by lee-jongwoo** [comment]
Solution:
```css
.memo_content {
  word-break: break-all;
  white-space: normal;
}
```
I'll fix this as soon as possible
